---
title: "DataViz Makerover 1"
description: |
  Assignment for course ISSS608, Visual Analytics and Application.
  
author:
  - name: LI Hongting
    url: https://www.linkedin.com/in/lihongting/
date: 01-23-2021
output:
  distill::distill_article:
    self_contained: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

#  1.0 Critique 

Correlation coefficient is a popular statistic that use to measure the type and strength of the relationship between two variables. 
 [Corrgram](http://www.datavis.ca/papers/corrgram.pdf) tend to be used to visually explore and analyse the structure and the patterns of relations among variables.  It is designed based on two main schemes:

- Rendering the value of a correlation to depict its sign and magnitude, and
- Reordering the variables in a correlation matrix so that "similar" variables are positioned adjacently, facilitating perception. 

In this hands-on exercise, you will learn how to plot data visualisation for visualising correlation matrix with R.  It consists of three main sections.  First, you will learn how to create correlation matrix using [*pairs()*](https://www.rdocumentation.org/packages/graphics/versions/3.6.0/topics/pairs) of R Graphics.  Next, you will learn how to plot corrgram using **corrplot** package of R Lastly, you will learn how to create an interactive correlation matrix using plotly R.   .  


#  2.0 Proposal and sketch-up

Before you get started, you are required:

- to start a new R project, and
- to create a new R Markdown document.

Next, you will use the code chunk below to install and launch **corrplot**,  **ggpubr**, **plotly** and **tidyverse** in RStudio.


#  3.0 Steps to create proposed chart in Tableau 

In this hands-on exercise, the [Wine Quality Data Set](https://archive.ics.uci.edu/ml/datasets/wine+quality) of UCI Machine Learning Repository will be used.  The data set consists of 13 variables and 6497 observations.  For the purpose of this exercise, we have combined the red wine and white wine data into one data file.  It is called wine_quality and is in csv file format.  


##  3.1 Importing Data

First, let us import the data into R by using *read_csv()*  of **readr** package.  

Notice that beside quality and type, the rest of the variables are numerical and continuous data type. 

##  3.2 Transform Data


##  3.3 Transform Data


#  4.0 Summary and Tableau Link

In the figure below, multiple histograms are plottted to reveal the distribution of the selected variables in the wine quality data sets.  
